引入了ant-design，可以加快开发
homkai/deef pull request #1
Opened 2017-07-11 14:07 UTC by DOCjx

感觉对框架还是有很多不懂的地方，路由只是自己简单的实现了下
相对与todomvc主要有以下变化
1. 引入ant-design，同时对ant-design的组件是按需加载
2. 在UI里面导入prop-types对传入的参数进行检测
3. 在webpack配置中利用less-loader的modifyVars选项覆盖ant-design的默认样式

2017-07-11 15:08 UTC, homkai commented on examples/exampleForAnt-Design/src/Root/modules/Test/UI.js
> +export default ({isLoading, onIncrease, onDecline, percent}) => {
export default ({isLoading, percent,  ...callbacks}) => {
    const {onIncrease, onDecline} = callbacks;
// 必须先解构状态，再解构callbacks，当callbacks大于1个的时候，推荐单独解构

2017-07-11 15:10 UTC, homkai commented on examples/exampleForAnt-Design/src/Root/modules/Test/UI.js
> +    selectedRowKeys: [3],  // Check here to configure the default column
怎么代码都不对齐的。。。

UI里就是单纯的渲染逻辑，什么状态，只可能是什么样的展现
不要在UI里搞一堆计算逻辑，更不可以在UI里定义callback，再简单的callback也要放到 connect的callbacks里

2017-07-11 15:11 UTC, homkai commented on examples/exampleForAnt-Design/src/Root/modules/Test/UI.js
> +	return (
UI文件太大的时候，必须拆成多个，不然很影响代码阅读

2017-07-11 15:15 UTC, homkai requested changes
你搞个eslint吧，写的代码太随意了

2017-07-11 15:15 UTC, homkai commented on examples/exampleForAnt-Design/src/Root/modules/Test/handler.js
> +	},800);
逗号后必须要加空格的。。。

2017-07-11 15:15 UTC, homkai commented on examples/exampleForAnt-Design/src/Root/modules/Test/models/test.js
> +			return{
必须使用 4个空格，对齐代码，不可使用tab

2017-07-11 15:15 UTC, homkai commented on examples/exampleForAnt-Design/src/Root/modules/Todo/UI.js
> +import React from 'react';
把Todo的代码删掉吧

2017-07-12 08:16 UTC, DOCjx commented
已经改好了，我再处理下代码复用的问题

2017-07-12 11:30 UTC, homkai requested changes

2017-07-12 11:30 UTC, homkai commented on examples/exampleForAnt-Design/src/Root/index.js
> +            })
必须加分号

2017-07-12 11:30 UTC, homkai commented on examples/exampleForAnt-Design/src/Root/index.js
> +            history.replace(`/${path}`);
不能这样搞，他报的warning的错误 可以先不管他  或者在顶层重写下push方法判断下

2017-07-12 11:30 UTC, homkai commented on examples/exampleForAnt-Design/src/Root/index.js
> +        onGoModule({dispatch, getState}, ...navInfo) {
大于两个参数的时候 用object传吧 就像{dispatch, getState} 这样，不容易记错顺序导致bug

2017-07-12 11:30 UTC, homkai commented on examples/exampleForAnt-Design/src/Root/modules/Test/UI/index.js
> +import {default as TableUI} from './Table.ui';
default 还需要 as 么

2017-07-12 11:30 UTC, homkai commented on examples/exampleForAnt-Design/src/Root/modules/Test/models/test.js
> +            const tmp  = state.tableData;
这个代码好丑  变量命名不要用 tmp这样的。。

hideTableLoading(state) {
  return {
   ...state,
   tabeData: {
    ...state.tabeData,
   loading: false
  }
  }
}

2017-07-12 15:21 UTC, DOCjx commented
好啦

2017-07-12 15:27 UTC, homkai approved these changes

2017-07-12 15:28 UTC, merged